# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 17:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('score_a', models.IntegerField(blank=True, null=True)),
                ('score_b', models.IntegerField(blank=True, null=True)),
                ('day', models.DateField()),
                ('hour', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_a', models.IntegerField(blank=True, null=True)),
                ('score_b', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('issue', models.IntegerField(blank=True, null=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='season.Fixture')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('newsletter', models.BooleanField(default=True)),
                ('reminder', models.BooleanField(default=True)),
                ('news_key', models.CharField(blank=True, max_length=50, null=True)),
                ('remind_key', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('points', models.IntegerField()),
                ('win', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('lose', models.IntegerField()),
                ('goal_for', models.IntegerField()),
                ('goal_against', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='table',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='season.Team'),
        ),
        migrations.AddField(
            model_name='leagueforecast',
            name='fourth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourth', to='season.Team'),
        ),
        migrations.AddField(
            model_name='leagueforecast',
            name='looser1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='looser1', to='season.Team'),
        ),
        migrations.AddField(
            model_name='leagueforecast',
            name='looser2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='looser2', to='season.Team'),
        ),
        migrations.AddField(
            model_name='leagueforecast',
            name='looser3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='looser3', to='season.Team'),
        ),
        migrations.AddField(
            model_name='leagueforecast',
            name='second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second', to='season.Team'),
        ),
        migrations.AddField(
            model_name='leagueforecast',
            name='third',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third', to='season.Team'),
        ),
        migrations.AddField(
            model_name='leagueforecast',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='season.Player'),
        ),
        migrations.AddField(
            model_name='leagueforecast',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='season.Team'),
        ),
        migrations.AddField(
            model_name='leagueforecast',
            name='winner_midseason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_midseason', to='season.Team'),
        ),
        migrations.AddField(
            model_name='forecast',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='season.Player'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='team_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_a', to='season.Team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='team_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_b', to='season.Team'),
        ),
    ]
