# Generated by Django 2.2.28 on 2022-07-07 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagueforecast',
            name='fifth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fifth', to='season.Team'),
        ),
        migrations.AddField(
            model_name='leagueforecast',
            name='looser4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='looser4', to='season.Team'),
        ),
        migrations.AlterField(
            model_name='leagueforecast',
            name='fourth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fourth', to='season.Team'),
        ),
        migrations.AlterField(
            model_name='leagueforecast',
            name='looser1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='looser1', to='season.Team'),
        ),
        migrations.AlterField(
            model_name='leagueforecast',
            name='looser2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='looser2', to='season.Team'),
        ),
        migrations.AlterField(
            model_name='leagueforecast',
            name='looser3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='looser3', to='season.Team'),
        ),
        migrations.AlterField(
            model_name='leagueforecast',
            name='second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second', to='season.Team'),
        ),
        migrations.AlterField(
            model_name='leagueforecast',
            name='third',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third', to='season.Team'),
        ),
        migrations.AlterField(
            model_name='leagueforecast',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to='season.Team'),
        ),
        migrations.AlterField(
            model_name='leagueforecast',
            name='winner_midseason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner_midseason', to='season.Team'),
        ),
    ]
