# Generated by Django 3.2.14 on 2023-07-04 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0002_league_forecasts_update_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leagueforecast',
            name='looser1',
        ),
        migrations.RemoveField(
            model_name='leagueforecast',
            name='looser2',
        ),
        migrations.RemoveField(
            model_name='leagueforecast',
            name='looser3',
        ),
        migrations.RemoveField(
            model_name='leagueforecast',
            name='looser4',
        ),
        migrations.AddField(
            model_name='leagueforecast',
            name='relegated1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relegated1', to='season.team'),
        ),
        migrations.AddField(
            model_name='leagueforecast',
            name='relegated2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relegated2', to='season.team'),
        ),
        migrations.AddField(
            model_name='leagueforecast',
            name='relegation_playoff1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relegation_playoff1', to='season.team'),
        ),
        migrations.AddField(
            model_name='leagueforecast',
            name='sixth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sixth', to='season.team'),
        ),
    ]
